language: python

python:
  - "3.4"
  - "3.6"
  - "nightly"

addons:
  apt:
    packages:
    - colordiff

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - "pip install pipenv"
  - "pipenv install --dev"

script:
 - pipenv run make test
