language: python

python:
  - "3.4"
  - "3.6"
  - "nightly"

addons:
  apt:
    packages:
    - colordiff

install:
  - "pip install -r requirements.txt"

script:
 - python --version
 - green tests/ --quiet-stdout
 - autopep8 -r . --diff | colordiff
 - find -name '*.py' | xargs flake8
