language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - "pip install -q beautifulsoup4"
  - "pip install -q autopep8"
  - "pip install -q requests"
# command to run tests
script:
 - python --version
 - python -m unittest discover tests/ -v
 - autopep8 -r . --diff