language: python
python:
  - "3.4"
  - "3.6"
  - "nightly"
install:
  - "pip install -r requirements.txt"
# command to run tests
script:
 - python --version
 - python -m unittest discover tests/ -v
 - autopep8 -r . --diff
 - find -name '*.py' | xargs flake8
